version: "2"
services:
  web:
    build: .
    ports:
    - "5050:5050"
    depends_on:
    - mongo
    environment:
      MONGO_URL: "mongodb://mongo:27017/wedding"
  mongo:
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
    - "27017:27017"